version: '3.8'
services:
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            # MYSQL_ROOT_HOST: "%"
            # MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - '${DATA_PATH_HOST}:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    
    nginx:
        build:
            context: "./docker/nginx"
        depends_on:
            -   php-fpm
        volumes:
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        ports:
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_HTTP_PORT}:80"
        networks:
            - sail

    php-fpm:
        build:
            context: "./docker/php-fpm"
        volumes:
            -   ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        networks:
            - sail
        expose:
            - "9000"
        environment:
            - "DB_HOST=mysql"
            - "DB_DATABASE=${DB_DATABASE}"
            - "DB_USERNAME=${DB_USERNAME}"
            - "DB_PASSWORD=${DB_PASSWORD}"
    
    # node:
    #     image: 'node:20-alpine'
    #     working_dir: ${APP_CODE_PATH_CONTAINER}
    #     volumes:
    #         - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    #         - ./docker/node/docker-entrypoint.sh:/docker-entrypoint.sh
    #     ports:
    #         - "${NODE_HOST_PORT}:5173"
    #     expose:
    #         - "5173"
    #     networks:
    #         - sail
    #     healthcheck:
    #         test: ["CMD", "node", "-v"]
    #         interval: 1m30s
    #         timeout: 30s
    #         retries: 5
    #         start_period: 30s
    #     environment:
    #         - NODE_ENV=development
    #         - NODE_HOST_PORT=${NODE_HOST_PORT}

networks:
    sail:
        driver: bridge